nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: Nico Trummer
  description: A single cell transcriptomics pipeline for QC, integration and making
    the results presentable
  force: false
  is_nfcore: true
  name: scdownstream
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 0.0.1dev
