name: seurat_integration
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-glmgampoi=1.18.0
  - bioconda::bioconductor-singlecellexperiment=1.28.0
  - conda-forge::r-seurat=5.1.0
