name: soupx
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::anndata2ri=1.3.2
  - bioconda::bioconductor-singlecellexperiment=1.24.0
  - conda-forge::leidenalg=0.10.2
  - conda-forge::python-igraph=0.11.8
  - conda-forge::r-soupx=1.6.2
  - conda-forge::scanpy=1.10.4
