name: celltypes_singler
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::anndata2ri=1.3.1
  - bioconda::bioconductor-celldex=1.12.0
  - bioconda::bioconductor-singlecellexperiment=1.24.0
  - bioconda::bioconductor-singler=2.4.0
  - conda-forge::anndata=0.10.7
